### ISSUE TITLE
Policy looking for public AMIs shows any/all regardless of owner.

### ISSUE THREAD

**Issue by jasonckeating** [PaloAltoNetworks/prisma-cloud-policies#30]
## Describe the bug

The policy `AWS Amazon Machine Image (AMI) is publicly accessible` shows **ALL** public AMIs as findings.

## Expected behavior

The intent of this rule is to alert on customer AMIs made public because:
AMIs may contain proprietary customer information and should be accessible only to authorized internal users.

We don't care what other AWS owners make public images.

## Current behavior

Currently seeing alerts for every public AMI, including amazon-provided.

## Steps to reproduce

Use an Amazon-provided image, check Prisma.

1.
2.
3.
4.

## Your Environment

- Version used:
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3):
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by jsreedharan-panw** [comment]
This was fixed in PCS-21.11.1 release
