### ISSUE TITLE
Configuration file in PAN doesn't contain local policies

### ISSUE THREAD

**Issue by npmguy** [PaloAltoNetworks/prisma-cloud-policies#38]
Do you know the reason why I can't see "rulebase" tag and local policies when I am executing "show running config" command on that device? What are the steps to include these policies to the config file? Maybe there is another command to fetch config + policies in the one output?

I would like to add that I need an xml output.... is possible?

-npmguy

**Comment by Montana** [comment]
Essentially, you just run the command: 
```bash
save config to <xml file name>
```
If you're using the CLI. From there, it's just a matter of downloading the XML file to wherever you want it. There appears to be no way to truly export policies, however they can be viewed in "set" format to make them easily importable by using the following commands:

```bash
set cli config-output-format set
```

From configure mode:

```bash
show rulebase security rules 
show rulebase (to view other policies)
```
I hope this helps.

**Comment by jsreedharan-panw** [comment]
This is not related to Prisma cloud.
